name: Fetch Property Data

on:
  schedule:
    - cron: "0 0 * * 0"  # Runs every Sunday at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-properties:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install firebase-admin requests

      - name: Create Firebase Key File
        run: echo "$FIREBASE_KEY" > firebase-key.json
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}

      - name: Run RentCast script
        env:
          RENTCAST_API_KEY: ${{ secrets.RENTCAST_API_KEY }}
        run: python rentcast_to_firebase.py
